WITH LATEST_SNAPSHOT AS
(
    SELECT PAYLOAD_ID, STATUS
    FROM MY_DATABASE.MY_SCHEMA.RAW_SOURCE_FRESHNESS
    WHERE PAYLOAD_TIMESTAMP_UTC >= (select MAX(PAYLOAD_TIMESTAMP_UTC) from MY_DATABASE.MY_SCHEMA.RAW_SOURCE_FRESHNESS)
),
GROUPED_RESULTS AS
(
    SELECT PAYLOAD_ID, STATUS, COUNT(STATUS) STATUS_COUNT
    FROM LATEST_SNAPSHOT
    GROUP BY PAYLOAD_ID, STATUS
),
PIVOT_RESULTS AS
(
    SELECT
        PAYLOAD_ID, IFNULL("'error'",0) as STALE, IFNULL("'warning'",0) as WARNING, IFNULL("'okay'",0) as OKAY
    FROM GROUPED_RESULTS    
    PIVOT(SUM(STATUS_COUNT) for STATUS in ('error', 'warning', 'okay'))
    
)
SELECT * FROM PIVOT_RESULTS
